#!/usr/bin/env bash
# Run once after: npm run tunnel:login
# Creates a named tunnel, copies credentials into cloudflared/, writes config.yml, adds DNS for frontend.yaadro.online.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CF_DIR="$ROOT/cloudflared"
TUNNEL_NAME="${CLOUDFLARE_TUNNEL_NAME:-frontend-yaadro-online}"
HOSTNAME="${CLOUDFLARE_TUNNEL_HOST:-frontend.yaadro.online}"

if [[ ! -f "${HOME}/.cloudflared/cert.pem" ]]; then
  echo "Missing ~/.cloudflared/cert.pem — run first: npm run tunnel:login"
  exit 1
fi

mkdir -p "$CF_DIR"

UUID=""
CRED_SRC=""

set +e
OUT=$(cloudflared tunnel create "$TUNNEL_NAME" 2>&1)
EC=$?
set -e
echo "$OUT"

if [[ "$EC" -eq 0 ]]; then
  # "Tunnel credentials written to /path/<uuid>.json"
  CRED_SRC=$(echo "$OUT" | sed -n 's/.*[Cc]redentials written to //p' | tr -d '\r' | awk '{print $1}')
  if [[ -n "${CRED_SRC}" && -f "${CRED_SRC}" ]]; then
    UUID=$(basename "${CRED_SRC}" .json)
  fi
  if [[ -z "$UUID" ]]; then
    UUID=$(echo "$OUT" | grep -oE '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}' | head -1)
    [[ -n "$UUID" ]] && CRED_SRC="${HOME}/.cloudflared/${UUID}.json"
  fi
else
  if echo "$OUT" | grep -qi 'already exists'; then
    echo "Tunnel name already in account; resolving UUID from list…"
    if ! command -v jq >/dev/null 2>&1; then
      echo "Install jq (brew install jq) to reuse an existing tunnel, or pick a new CLOUDFLARE_TUNNEL_NAME."
      exit 1
    fi
    UUID=$(cloudflared tunnel list --output json | jq -r --arg n "$TUNNEL_NAME" '.[] | select(.name == $n) | .id' | head -1)
    if [[ -z "$UUID" || "$UUID" == "null" ]]; then
      echo "Could not find tunnel named: $TUNNEL_NAME"
      exit 1
    fi
    CRED_SRC="${HOME}/.cloudflared/${UUID}.json"
  else
    exit 1
  fi
fi

if [[ -z "$UUID" ]]; then
  echo "Could not determine tunnel UUID. Check cloudflared output above."
  exit 1
fi

if [[ ! -f "${CRED_SRC}" ]]; then
  echo "Credentials file not found: ${CRED_SRC}"
  exit 1
fi

cp "${CRED_SRC}" "${CF_DIR}/credentials.json"
echo "Copied credentials to cloudflared/credentials.json"

cat >"${CF_DIR}/config.yml" <<EOF
# Generated by scripts/bootstrap-cloudflare-tunnel.sh — edit ingress if PORT changes.
# credentials-file is resolved from repo root (run: npm run tunnel).
tunnel: ${UUID}
credentials-file: cloudflared/credentials.json

ingress:
  - hostname: ${HOSTNAME}
    service: http://127.0.0.1:4100
  - service: http_status:404
EOF

echo "Wrote cloudflared/config.yml (tunnel: ${UUID})"

echo "Adding DNS route ${HOSTNAME} (ok if it already exists)…"
cloudflared tunnel route dns "$TUNNEL_NAME" "$HOSTNAME" || true

echo "Done. In one terminal: npm run dev  |  In another: npm run tunnel"
